"""Frama-C/WP backend: ACSL contracts on the target function, RTE assertions
generated by Frama-C, everything discharged by SMT solvers (Alt-Ergo, and
Z3 when installed).

Settings ([backend.framac] in config.toml, all optional):
  framac_bin    = "frama-c"
  provers       = "alt-ergo"        comma-separated, in WP's syntax
  prover_timeout_seconds = 10       per goal

Per check, the backend writes one C file into its workspace: the original
source with the target function replaced by the annotated submission, every
other function definition reduced to a prototype (callees with an accepted
contract get it attached), and runs

  frama-c -wp -wp-rte -wp-fct <fn> -wp-print ...

Frama-C ships ACSL specifications for the C library, so calls to memcpy,
strlen and friends need no trusted spec from the project.
"""

from __future__ import annotations

import re
import shlex
from pathlib import Path
from typing import Any

from fver.backends.base import (
    AuditResult,
    CheckOutcome,
    CheckResult,
    FunctionTask,
    PromptContext,
    Submission,
    SubmissionSpec,
    TranslateResult,
)
from fver.backends.framac import acsl
from fver.backends.framac.parse_output import classify
from fver.backends.refinedc import annotations as ann
from fver.core.models import FunctionInfo, Target, TranslationUnit, sha256_text
from fver.index.functions import extract_from_source
from fver.util import platform as plat
from fver.util.proc import run, version_of, which

_PROMPTS_DIR = Path(__file__).parent / "prompts"
INSTALL_HINT = "run `fver setup`"

# ACSL that would let a proof through without proving anything.
FORBIDDEN = [
    (r"\badmit\b", "`admit` (an unproved assumption)"),
    (r"\baxiom\b", "`axiom` (an unproved assumption)"),
    (r"\baxiomatic\b", "`axiomatic` (may hide axioms)"),
    (r"\bassumes\b", "`assumes` behaviours (a contract must cover every call)"),
    (r"\bghost\b", "ghost code (keep the C as it is)"),
    (r"requires\s+\\false\b", "`requires \\false` (no caller could satisfy it)"),
    (r"^\s*#\s*(include|define)\b", "preprocessor directives"),
]


def _flags_from(arguments: list[str]) -> list[str]:
    """The -I and -D flags the file is read with."""
    out: list[str] = []
    skip = False
    for a in arguments[1:]:
        if skip:
            out.append(a)
            skip = False
            continue
        if a in ("-I", "-D", "-U", "-include"):
            out.append(a)
            skip = True
        elif a.startswith(("-I", "-D", "-U")):
            out.append(a)
    return out


class FramaCBackend:
    name = "framac"

    def __init__(self, workspace_dir: Path, settings: dict[str, Any], target: Target):
        self.workspace_dir = Path(workspace_dir)
        self.workspace_dir.mkdir(parents=True, exist_ok=True)
        self.settings = dict(settings or {})
        self.target = target
        self.framac_bin: str = self.settings.get("framac_bin") or plat.tool("frama-c")
        self.provers: str = self.settings.get("provers") or "alt-ergo"
        self.prover_timeout: int = int(self.settings.get("prover_timeout_seconds") or 10)
        self._versions: dict[str, str] | None = None

    # ----------------------------------------------------------------- tools

    def tool_versions(self) -> dict[str, str]:
        if self._versions is None:
            v: dict[str, str] = {}
            ver = version_of([self.framac_bin, "-version"])
            if ver:
                v["frama-c"] = ver.strip().splitlines()[0]
            for p in self.provers.split(","):
                p = p.strip()
                exe = plat.tool(p)
                pv = version_of([exe, "--version"]) if which(exe) else None
                if pv:
                    v[p] = pv.strip().splitlines()[0][:40]
            self._versions = v
        return dict(self._versions)

    def _machdep(self) -> str:
        return "gcc_x86_64" if self.target.pointer_bits == 64 else "gcc_x86_32"

    def _base_argv(self, tu: TranslationUnit | None) -> list[str]:
        flags = _flags_from(tu.arguments) if tu else []
        argv = [self.framac_bin, "-machdep", self._machdep()]
        if flags:
            argv += ["-cpp-extra-args=" + " ".join(shlex.quote(f) for f in flags)]
        return argv

    def _env(self) -> dict[str, str]:
        import os

        env = dict(os.environ)
        env["PATH"] = str(plat.switch_bin()) + os.pathsep + env.get("PATH", "")
        return env

    # --------------------------------------------------------------- prepare

    def prepare(self, tus: list[TranslationUnit], repo_root: Path) -> None:
        if which(self.framac_bin) is None:
            from fver.backends.base import BackendToolMissing

            raise BackendToolMissing(f"`{self.framac_bin}` not found: {INSTALL_HINT}")

    # ------------------------------------------------------------- translate

    def translate(
        self, tu: TranslationUnit, functions: list[FunctionInfo], repo_root: Path
    ) -> TranslateResult:
        """Frama-C parses the whole file or nothing: a parse error makes every
        function unsupported with that reason."""
        src = repo_root / tu.source_path
        argv = self._base_argv(tu) + ["-no-autoload-plugins", str(src)]
        r = run(argv, cwd=repo_root, timeout=300, env=self._env())
        supported = {f.name: True for f in functions}
        if r.returncode == 0:
            return TranslateResult(supported=supported)
        err = r.stderr.strip() or r.stdout.strip()
        m = re.search(r"\[kernel[^\]]*\] ([^\n]*[Ee]rror[^\n]*)", r.stdout + "\n" + r.stderr)
        reason = (m.group(1) if m else err.splitlines()[-1] if err else "frama-c failed")[:300]
        return TranslateResult(
            supported={f.name: False for f in functions},
            reasons={f.name: reason for f in functions},
            tu_error=reason,
        )

    # ---------------------------------------------------------------- prompt

    def submission_spec(self) -> SubmissionSpec:
        return SubmissionSpec(
            files={
                "function.c": "the target function with ACSL annotations; code otherwise unchanged"
            },
            required=["function.c"],
            language_hints={"function.c": "c"},
        )

    def prompt_context(self) -> PromptContext:
        def read(name: str) -> str:
            p = _PROMPTS_DIR / name
            return p.read_text(encoding="utf-8", errors="replace") if p.exists() else ""

        return PromptContext(
            reference=read("reference.md"),
            examples=read("examples.md"),
            instructions=read("instructions.md"),
            forbidden_patterns=[pat for pat, _ in FORBIDDEN],
        )

    # ------------------------------------------------------------- guardrail

    def guardrail(self, submission: Submission) -> list[str]:
        problems: list[str] = []
        fn = submission.files.get("function.c")
        if fn is None:
            return ["submission is missing function.c"]
        for pat, why in FORBIDDEN:
            if re.search(pat, fn, re.MULTILINE):
                problems.append(f"forbidden: {why}")
        for name in submission.files:
            if name != "function.c":
                problems.append(f"unexpected file in submission: {name}")
        return problems

    # ----------------------------------------------------------------- check

    def _build_source(self, task: FunctionTask, annotated_fn: str) -> str:
        """The original file with the target replaced by the submission,
        every other definition reduced to a prototype, and each callee's
        accepted contract attached to its prototype (same file) or declared
        after the includes (other files)."""
        base = task.source_text
        contracts = {**task.external_specs, **task.callee_specs}
        declared: list[str] = []
        stubs: dict[str, str] = {}
        for cname, contract in contracts.items():
            if cname == task.function.name:
                continue
            if ann.find_definition_range(base, cname) is not None:
                stubs[cname] = acsl.one_line(contract) + ";"
            else:
                declared.append(contract.rstrip().rstrip(";") + ";")
        for other in extract_from_source(base, task.function.source_path, task.tu.id):
            if other.name == task.function.name:
                continue
            if (
                other.start_line <= task.function.end_line
                and other.end_line >= task.function.start_line
            ):
                continue
            if other.name in stubs:
                lines = base.split("\n")
                body = lines[other.start_line - 1 : other.end_line]
                kept = [ln if ln.lstrip().startswith("#") else "" for ln in body]
                kept[0] = stubs[other.name] if not kept[0] else stubs[other.name] + " " + kept[0]
                lines[other.start_line - 1 : other.end_line] = kept
                base = "\n".join(lines)
            else:
                base = ann.stub_definition(base, other.start_line, other.end_line)
        lines = base.split("\n")
        new = acsl.split_calls_declarations(annotated_fn.rstrip("\n")).split("\n")
        lines[task.function.start_line - 1 : task.function.end_line] = new
        out = "\n".join(lines)
        if declared:
            out = ann.prepend_prototypes(out, declared)
        return out

    def _check_argv(self, c_file: Path, tu: TranslationUnit, fn: str) -> list[str]:
        return self._base_argv(tu) + [
            str(c_file),
            "-wp",
            "-wp-rte",
            "-wp-fct",
            fn,
            "-wp-prover",
            self.provers,
            "-wp-timeout",
            str(self.prover_timeout),
            "-wp-par",
            "4",
            "-wp-print",
            "-wp-prop=-@terminates,-@exits",  # neither non-termination nor exit() is UB
            "-warn-invalid-pointer",
            "-warn-left-shift-negative",
            "-warn-right-shift-negative",
        ]

    def check(
        self, task: FunctionTask, submission: Submission, timeout_seconds: int
    ) -> CheckResult:
        problems = self.guardrail(submission)
        annotated = submission.files.get("function.c", "")
        if annotated:
            same, why = ann.code_unchanged(task.function_text, annotated)
            if not same:
                problems.append(
                    why.replace("rc:: attributes, ghost statements and comments", "ACSL comments")
                )
        if problems:
            return CheckResult(
                outcome=CheckOutcome.GUARDRAIL,
                feedback="Submission rejected before checking:\n- " + "\n- ".join(problems),
            )
        wd = Path(task.workdir)
        wd.mkdir(parents=True, exist_ok=True)
        c_file = wd / Path(task.function.source_path).name
        source = self._build_source(task, annotated)
        c_file.write_text(source, encoding="utf-8")
        artifacts = {"source": str(c_file)}
        if which(self.framac_bin) is None:
            return CheckResult(
                outcome=CheckOutcome.TOOL_ERROR,
                feedback=f"`{self.framac_bin}` not found. {INSTALL_HINT}",
                artifacts=artifacts,
            )
        r = run(
            self._check_argv(c_file, task.tu, task.function.name),
            cwd=task.repo_root,
            timeout=timeout_seconds,
            env=self._env(),
        )
        (wd / "wp.log").write_text(r.stdout + "\n--- stderr ---\n" + r.stderr, encoding="utf-8")
        artifacts["log"] = str(wd / "wp.log")
        src_lines = source.split("\n")

        def source_line(n: int) -> str | None:
            return src_lines[n - 1] if 1 <= n <= len(src_lines) else None

        cl = classify(
            r.stdout, r.stderr, r.returncode, r.timed_out, task.function.name, source_line
        )
        feedback = cl.feedback
        if cl.missing_specs and cl.outcome is not CheckOutcome.OK:
            feedback += "\nno contract for callee " + ", ".join(cl.missing_specs)
        proof_hash = None
        if cl.outcome is CheckOutcome.OK:
            proof_hash = sha256_text(source + "\n" + submission.content_hash())
        assumptions = [f"callee:{n}" for n in task.callee_specs] + [
            f"external:{n}" for n in task.external_specs
        ]
        return CheckResult(
            outcome=cl.outcome,
            feedback=feedback,
            goals=cl.goals,
            stdout=r.stdout,
            stderr=r.stderr,
            artifacts=artifacts,
            proof_hash=proof_hash,
            assumptions=assumptions,
            tool_versions=self.tool_versions(),
            duration_seconds=r.duration,
        )

    # ----------------------------------------------------------------- audit

    def audit(self, task: FunctionTask, result: CheckResult) -> AuditResult:
        """WP has no assumption printer; the guardrail already rejects every
        ACSL construct that could smuggle an assumption in, so the audit
        re-checks the file that was actually verified and records what the
        proof trusts: Frama-C, the solvers, and the C library specs."""
        src = Path(result.artifacts.get("source", ""))
        violations: list[str] = []
        if src.exists():
            text = src.read_text(encoding="utf-8", errors="replace")
            for pat, why in FORBIDDEN[:3]:
                if re.search(pat, text, re.MULTILINE):
                    violations.append(f"verified file contains {why}")
        if violations:
            return AuditResult(passed=False, violations=violations)
        assumptions = [f"tool:{k}={v}" for k, v in self.tool_versions().items()]
        assumptions.append("libc:frama-c-acsl-specs")
        return AuditResult(
            passed=True, assumptions=sorted(set(result.assumptions) | set(assumptions))
        )

    # ---------------------------------------------------------------- spec

    def extract_spec(self, submission: Submission, function: FunctionInfo) -> str:
        return acsl.extract_contract(submission.files.get("function.c", ""))
