"""Facts about RefinedC's CLI, file layout, annotation language and output.

Every constant here was checked against a real install on 2026-09-12:
refinedc 2e89846 (gitlab.mpi-sws.org/iris/refinedc, master), Rocq 9.1.0,
dune 3.23, in an opam switch. Items marked CONFIRMED were exercised end to
end; items marked DOC come from RefinedC's ANNOTATIONS.md / README.md and
were not exercised separately. Nothing else in the backend should hardcode
any of this.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Binaries (CONFIRMED). There is no separate `cerberus` binary: the Cerberus
# front-end is a library linked into `refinedc`.
# ---------------------------------------------------------------------------
REFINEDC_BIN = "refinedc"
COQC_BIN = "coqc"  # Rocq 9 still installs a `coqc` wrapper next to `rocq`.
ROCQ_BIN = "rocq"
DUNE_BIN = "dune"
OPAM_BIN = "opam"

# ---------------------------------------------------------------------------
# CLI (CONFIRMED from `refinedc check --help` / `refinedc init --help`)
# ---------------------------------------------------------------------------
INIT_ARGV = ["init"]  # run inside the project directory; creates PROJECT_FILE
INIT_COQ_PATH_FLAG = "--coq-path={path}"  # dot-separated identifiers
CHECK_ARGV = ["check"]  # `refinedc check [OPTION]... FILE.c`
NO_BUILD_FLAG = "--no-build"  # front-end + code generation only, no Rocq build
NO_EXTRA_ANALYSIS_FLAG = "--no-extra-analysis"  # silence the two heuristic warnings
INCLUDE_FLAG_FMT = "-I{dir}"
DEFINE_FLAG_FMT = "-D{macro}"
INCLUDE_FILE_FLAG_FMT = "--include={file}"
VERSION_ARGV = ["--version"]  # prints e.g. `2e89846-dirty`

# Preprocessing (CONFIRMED from frontend/cerb_wrapper.ml): RefinedC runs
#   cc -E -C -Werror -nostdinc -undef -I<cerberus libc include> [-I dirs from
#   rc-project.toml [cpp].include] [-I from the command line] -D__refinedc__
#   -D__cerb__ -DDEBUG -DMAX_CPUS=4 -DMAX_VMS=2 -DHEAP_PAGES=10 [-D...]
# The system headers are Cerberus's own libc, so <setjmp.h>, floating point
# and other unsupported features fail here, not later.
PREDEFINED_MACROS = ("__refinedc__", "__cerb__")

# Exit codes (CONFIRMED): 0 success; 1 front-end error or failed Rocq build;
# 125 internal error (an uncaught OCaml exception, e.g. a malformed
# attribute string crashes the annotation parser).
EXIT_INTERNAL_ERROR = 125

# ---------------------------------------------------------------------------
# Project layout (CONFIRMED)
# ---------------------------------------------------------------------------
PROJECT_FILE = "rc-project.toml"
# Exactly what `refinedc init` writes (plus comments); coq_root defaults to
# refinedc.project.<dirname> and every path segment must be a Coq identifier.
PROJECT_FILE_TEMPLATE = (
    "# Generated by fver (mirrors `refinedc init`).\n\n"
    'coq_root = "{coq_root}"\n\n'
    "[cpp]\n"
    "include = []\n"
    "use_rc_include = true\n\n"
    "[coq]\n"
    "extra_theories = []\n"
)
DEFAULT_COQ_ROOT = "refinedc.project.fver"
OTHER_PROJECT_FILES = ("_CoqProject", "dune-project")  # also written by init

# For <project>/<dir>/<stem>.c the generated files land in
# <project>/<dir>/proofs/<stem>/ (CONFIRMED: src/example.c -> src/proofs/example/).
PROOFS_DIR_NAME = "proofs"
GENERATED_CODE = "generated_code.v"
GENERATED_SPEC = "generated_spec.v"
GENERATED_PROOF_FMT = "generated_proof_{fn}.v"
GENERATED_DUNE = "dune"
GENERATED_PROOF_LIST = "proof_files"
# Coq module path of that directory: <coq_root>.<dir parts>.<stem>
# (CONFIRMED: `From refinedc.project.rcproj.zero2 Require Import generated_code.`).
# dune compiles into <project>/_build/default/<dir>/proofs/<stem>/ (CONFIRMED).
DUNE_BUILD_DIR = "_build/default"
# Generated Coq names (CONFIRMED).
PROOF_LEMMA_FMT = "type_{fn}"
SPEC_DEF_FMT = "type_of_{fn}"
IMPL_DEF_FMT = "impl_{fn}"

# ---------------------------------------------------------------------------
# Header and annotations (CONFIRMED against ANNOTATIONS.md and by use)
# ---------------------------------------------------------------------------
HEADER_INCLUDE = "#include <refinedc.h>"
HEADER_NAMES = ("refinedc.h",)
ATTR_PREFIX = "rc::"

ATTR_PARAMETERS = "rc::parameters"
ATTR_ARGS = "rc::args"
ATTR_RETURNS = "rc::returns"
ATTR_REQUIRES = "rc::requires"
ATTR_ENSURES = "rc::ensures"
ATTR_EXISTS = "rc::exists"
ATTR_TACTICS = "rc::tactics"
ATTR_LEMMAS = "rc::lemmas"
ATTR_INV_VARS = "rc::inv_vars"
ATTR_CONSTRAINTS = "rc::constraints"
ATTR_REFINED_BY = "rc::refined_by"
ATTR_FIELD = "rc::field"
ATTR_GLOBAL = "rc::global"
ATTR_CONTEXT = "rc::context"
ATTR_INSTANTIATE = "rc::instantiate"

# Escape hatches: no proof is generated / the spec is trusted (CONFIRMED in docs).
FORBIDDEN_ATTRIBUTES = ("rc::trust_me", "rc::skip", "rc::manual_proof")
# `//@rc::<directive>` comment directives (DOC, ANNOTATIONS.md "Annotations
# using comments"). `import`/`require` pull in arbitrary Coq modules and
# `inlined*` inject arbitrary Coq code into the generated files, so the LLM
# may not use them; the backend writes the single import it needs itself.
DIRECTIVE_PREFIX = "//@rc::"
LLM_FORBIDDEN_DIRECTIVES = (
    "import",
    "require",
    "inlined",
    "inlined_prelude",
    "inlined_final",
    "context",
    "typedef",
)
LLM_FORBIDDEN_ATTRIBUTES = FORBIDDEN_ATTRIBUTES + ("rc::annot_args",)

# Ghost macros from refinedc.h (CONFIRMED from the header): semantically
# no-ops, may be added by the annotator.
GHOST_STATEMENT_PREFIX = "rc_"
GHOST_STATEMENTS = (
    "rc_unfold",
    "rc_unfold_int",
    "rc_annot",
    "rc_unlock",
    "rc_to_uninit",
    "rc_stop",
    "rc_share",
    "rc_unfold_once",
    "rc_learn",
    "rc_learn_alignment",
    "rc_reduce_expr",
    "rc_assert",
)

# ---------------------------------------------------------------------------
# Helper lemmas (CONFIRMED end to end)
# ---------------------------------------------------------------------------
# A file lemmas.v placed in the generated proofs directory is compiled by the
# generated dune theory automatically (the theory covers every .v in the
# directory). It is imported into the proof files by the comment directive
#     //@rc::import lemmas from <coq_root>.<modpath>
# which the backend inserts after the includes. Lemmas mentioning RefinedC
# `type`s must live in a Section with `Context `{!typeG Σ}.`; `rc::tactics`
# / `rc::lemmas` then apply them.
LEMMAS_FILE = "lemmas.v"
LEMMAS_MODULE = "lemmas"
IMPORT_DIRECTIVE_FMT = "//@rc::import {module} from {path}"
LEMMAS_PRELUDE = "From refinedc.typing Require Import typing."

# Line-number calibration (CONFIRMED). Coq-level messages (`Location:`,
# `at "file" [...]`, LocationInfo in generated_code.v) give the physical line
# of the `cc -E -C` output, not the source line: every include expansion
# shifts them by a constant, blank/comment/#define lines count one each, a
# run of more than 8 blank lines collapses to one line marker. Front-end
# errors (`[file:line:col] ...`) use real source lines. The backend inserts
# this unannotated marker function right after the includes; its `return`
# statement's LocationInfo line minus its source line is the offset.
LINE_MARKER_FN = "__fver_line_marker"
LINE_MARKER_TEXT = "static int __fver_line_marker(void) { return 0; }"
LOCATION_INFO_REGEX = (
    r"Definition\s+(?P<name>loc_\d+)\s*:\s*location_info\s*:=\s*LocationInfo\s+"
    r"(?P<file>file_\d+)\s+(?P<l1>\d+)\s+(?P<c1>\d+)\s+(?P<l2>\d+)\s+(?P<c2>\d+)"
)
FILE_DEF_REGEX = r'Definition\s+(?P<name>file_\d+)\s*:\s*string\s*:=\s*"(?P<path>[^"]*)"'

# ---------------------------------------------------------------------------
# Forbidden Coq vocabulary in LLM-written lemmas.v (CONFIRMED semantics)
# ---------------------------------------------------------------------------
FORBIDDEN_COQ_PATTERNS = (
    r"\bAdmitted\b",
    r"\badmit\b",
    r"\bgive_up\b",
    r"\bAxiom\b",
    r"\bAxioms\b",
    r"\bParameter\b",
    r"\bParameters\b",
    r"\bHypothesis\b",
    r"\bHypotheses\b",
    r"\bConjecture\b",
    r"\bDeclare\s+ML\s+Module\b",
    r"\bUnset\s+Guard\s+Checking\b",
    r"\bUnset\s+Positivity\s+Checking\b",
    r"\bUnset\s+Universe\s+Checking\b",
    r"\bUnset\s+Strict\s+Universe\s+Declaration\b",
    r"\bLtac2\s+@\s*external\b",
    r"\bRequire\s+Extraction\b",
)

# ---------------------------------------------------------------------------
# Output (CONFIRMED from captured runs; see tests/fixtures/refinedc/)
# ---------------------------------------------------------------------------
# Output carries ANSI colour codes (red for errors, yellow for warnings).
ANSI_REGEX = r"\x1b\[[0-9;]*m"
SUCCESS_MARKER = "successfully checked."  # `File "x.c" successfully checked.`
DUNE_FAILED_MARKER = "The call to [dune] returned with error code"
INTERNAL_ERROR_MARKER = "internal error"  # `refinedc: internal error, uncaught exception:`
# Front-end: `[file:line:col-col] Frontend error.` + an explanation line, or
# `[file:line:col-col (cursor: ...)] Not implemented: expr va_end`, or
# `[file:line:col:] Not implemented: layout_of (Basic float)`, or a cpp
# error `path/setjmp.h:15:2: error: <setjmp.h> is not currently supported`.
FRONTEND_ERROR_MARKERS = (
    "Frontend error.",
    "Not implemented:",
    "feature not yet supported",
    "is not currently supported",
    "error:",
    "Panic",
)
# Warnings from the extra analyses; never errors.
WARNING_MARKERS = (
    "potentially introduces non-determinism",
    "address of a local variable",
)
FRONTEND_LOCATION_REGEX = r"\[(?P<file>[^\[\]:]+):(?P<line>\d+):(?P<col>\d+)(?::?-?[^\]]*)?\]"
CPP_LOCATION_REGEX = r"(?P<file>[^\s:]+\.[ch]):(?P<line>\d+):(?P<col>\d+):\s*(?:fatal\s+)?error:"
# Lithium / proof failures inside a generated proof file.
STUCK_MARKER = "Type system got stuck in function"  # ... "f" in block "#0" !
SIDECOND_MARKER = "Cannot solve side condition in function"  # ... "f" !
LOCATION_REGEX = r'Location:\s*"(?P<file>[^"]+)"\s*\[\s*(?P<l1>\d+)\s*:\s*(?P<c1>\d+)\s*-\s*(?P<l2>\d+)\s*:\s*(?P<c2>\d+)\s*\]'
AT_LOCATION_REGEX = r'at\s+"(?P<file>[^"]+)"\s*\[\s*(?P<l1>\d+)\s*:\s*(?P<c1>\d+)\s*-\s*(?P<l2>\d+)\s*:\s*(?P<c2>\d+)\s*\]'
CASE_MARKER = "Case distinction"
GOAL_HEADER = "Goal:"
GOAL_SEPARATOR = "---------------------------------------"  # hypotheses / conclusion
GOAL_SEPARATOR_IRIS = "--------------------------------------∗"  # spatial context
COQ_FILE_ERROR_REGEX = r'File "(?P<file>[^"]+)", line (?P<line>\d+), characters (?P<chars>[\d-]+):'
COQ_ERROR_MARKER = "Error:"
INCOMPLETE_PROOF_MARKER = "Attempt to save an incomplete proof"
# UB detected by the front-end is not something we observed RefinedC report
# statically; kept for the (rare) Cerberus messages that name it.
UB_MARKERS = ("undefined behaviour", "undefined behavior")

# ---------------------------------------------------------------------------
# Audit (CONFIRMED)
# ---------------------------------------------------------------------------
#   coqc -Q <project>/_build/default/<dir>/proofs/<stem> <coq_root>.<modpath> audit_<fn>.v
# with the audit file containing AUDIT_SCRIPT_FMT prints either
# `Closed under the global context` or `Axioms:` followed by `name : type`
# lines. Takes ~2.5 s. The installed RefinedC/Iris/stdpp theories are found
# through the switch's user-contrib without extra flags.
AUDIT_FILE_FMT = "audit_{fn}.v"
AUDIT_SCRIPT_FMT = (
    "From {coq_root}.{modpath} Require Import {proof_module}.\nPrint Assumptions {lemma}.\n"
)
AUDIT_CLOSED_MARKER = "Closed under the global context"
AUDIT_AXIOMS_HEADER = "Axioms:"
# RefinedC's own examples are closed under the global context, so the
# allow-list is only for axioms stdpp/Iris may introduce in some setups.
ALLOWED_AXIOMS = frozenset(
    {
        "functional_extensionality_dep",
        "propositional_extensionality",
        "proof_irrelevance",
        "classic",
        "Classical_Prop.classic",
        "constructive_indefinite_description",
        "Eqdep.Eq_rect_eq.eq_rect_eq",
        "JMeq_eq",
        "epsilon_statement",
    }
)

# ---------------------------------------------------------------------------
# Behaviour (CONFIRMED)
# ---------------------------------------------------------------------------
# 1. Functions without rc:: attributes are translated to Coq (generated_code.v
#    has their impl) but no spec or proof is generated ("has been skipped").
# 2. A prototype carrying rc:: attributes (no body in the file) gets a
#    type_of_<fn> spec and calls to it are checked against that spec; this is
#    how verified callees and trusted externals are introduced.
# 3. `refinedc check` exits 0 only if the front-end accepts the whole file and
#    every generated proof compiles; `--no-build` exits 0 after the front-end.
# 4. Timing: a one-loop function with a helper lemma takes 5-8 s end to end;
#    the front-end alone is under 0.5 s; the Rocq build dominates.
# 5. Unsupported in the front-end: floating point anywhere in the types the
#    file sees (`layout_of (Basic float)`), <setjmp.h>, varargs (`va_end` not
#    implemented), casts inside integer constant expressions (array sizes
#    like `char b[(int)(16 * sizeof(void*))]`), and some struct layouts crash
#    the front-end (`Tags definitions must be set`). goto, switch, function
#    pointers (with function_ptr<...> types), unions (rc::union_tag) and
#    bit-level ops are supported.
